# Generated by Django 2.2.2 on 2019-06-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='menu',
            new_name='product',
        ),
    ]
