# Generated by Django 2.2.2 on 2019-06-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190628_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='product',
        ),
    ]
