# Generated by Django 3.0 on 2020-02-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='defalt.jpg', upload_to='restaurant_pics'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
